services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-root}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-docker}
      POSTGRES_DB: ${DATABASE_NAME:-arcade}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    restart: always
    ports:
      - "4000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ../:/app
      - /app/node_modules
    command: yarn start:dev
    depends_on:
      - db
      - redis

volumes:
  postgres_data: